require'nvim-treesitter.configs'.setup{
  ensure_installed = {
    'bash',
    'bibtex',
    'css',
    'graphql',
    'html',
    'javascript',
    'json',
    'jsdoc',
    'jsonc',
    'latex',
    'lua',
    'org',
    'swift',
    'toml',
    'yaml',
  },
  highlight = {
    enable = true,
    disable = {'org'},
    additional_vim_regex_highlighting = {'org'},
  },
  indent = { enable = true },
  incremental_selection = { enable = true },
}
