#!/usr/bin/env sh

yabai -m config status_bar                   on
yabai -m config status_bar_text_font        "Dank Mono:Regular:12.0"
yabai -m config status_bar_background_color  0xff121212
yabai -m config status_bar_foreground_color  0xff5cafb0
yabai -m config status_bar_space_icon_strip  Comms Write Design Code Preview Learn Jam VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_shadow                float
yabai -m config window_border                on
yabai -m config window_border_width          1
yabai -m config active_window_border_color   0xff5cafb0
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0f
yabai -m config normal_window_opacity        1.0f
yabai -m config split_ratio                  0.5
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

yabai -m config layout                       bsp
yabai -m config top_padding                  30
yabai -m config bottom_padding               30
yabai -m config left_padding                 30
yabai -m config right_padding                30
yabai -m config window_gap                   30

echo "yabai configuration loaded.."
