#!/usr/bin/env sh

yabai -m config external_bar                 all:26:0

yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off

yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

yabai -m config auto_balance                 off
yabai -m config split_ratio                  0.5

yabai -m config window_placement             second_child
yabai -m config window_topmost               off 
yabai -m config window_shadow                float
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

yabai -m config window_border on
yabai -m config window_border_width 1
yabai -m config active_window_border_color   0xff5cafb0
yabai -m config normal_window_border_color   0x995cafb0
yabai -m config insert_feedback_color        0xffe68e8e
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

yabai -m config layout bsp

yabai -m rule --add app="System Preferences" manage=off layer=above
