#!/usr/bin/env sh

yabai -m config mouse_follows_focus off

yabai -m config window_border on
yabai -m config window_border_width 1
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555556
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config top_padding 30
yabai -m config bottom_padding 30
yabai -m config left_padding 30
yabai -m config right_padding 30
yabai -m config window_gap 30

yabai -m config layout bsp
