add_newline = false

[character]
symbol = "▷"
success_symbol = "[▷](bold green)"
error_symbol = "▶"
use_symbol_for_status = true

[directory]
truncation_length = 1
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[git_status]
disabled = true

[git_branch]
disabled = true
