add_newline = false

[character]
success_symbol = "[▷](bold green)"
error_symbol = "▶"

[directory]
truncation_length = 1
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[git_status]
disabled = true

[git_state]
disabled = true

[git_commit]
disabled = true

[git_branch]
disabled = true
