export PATH="$PATH:$(yarn global bin):$HOME/.composer/vendor/bin"
export EDITOR='vim'
export VISUAL='vim'
export ZSHRC='~/.zshrc'
export VIMRC='~/.vimrc'

# Load Node Version Manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"

# Load Wasmer
export WASMER_DIR="$HOME/.wasmer"
[ -s "$WASMER_DIR/wasmer.sh" ] && source "$WASMER_DIR/wasmer.sh"

# Some core aliases
alias vi='vim'
alias reload="source $ZSHRC"
alias zshrc='vi $ZSHRC'
alias vimrc='vi $VIMRC'

# Replace ls and la with exa
alias ls='exa --long --group-directories-first'
alias la='exa -abghl --git --color=automatic'

# Replace tree with exa
# --git-ignore only works if ignore pattern doesn't have slashes
# See: https://github.com/ogham/exa/commit/827aa8bfc32eadf353f72b0ce41c88dc4ad411c1
alias tree='exa -T --group-directories-first --git-ignore'

# Set git as an alias of hub
eval "$(hub alias -s)"

# Create a new directory and enter it.
# https://github.com/jmegs/dotfiles/blob/master/zshrc#L24-L27
mkd() {
  mkdir -p "$@" && cd "$_";
}

# Create directory and subdirectories if they do not exist.
mkp() {
  mkdir -p "$@";
}

